Docker astrometry
AstroHuntsman/huntsman-drp pull request #43
Opened 2020-10-07 00:15 UTC by fergusL

PR includes changes to add astrometry.net functionality to the huntsman-drp docker container. Also includes a python script that can be pointed at a directory containing fits images to process the astrometry of the files

2020-10-07 01:49 UTC, danjampro requested changes
Hi @fergusL, thanks for your work on this - looks good. I've included a fair few comments, mainly about reorganising / tidying up the code and making things a bit more consistent with the rest of `huntsman-drp`. Happy to discuss any of these with you if they are not clear / don't make sense.

2020-10-07 01:49 UTC, danjampro commented on scripts/download_index_files.sh
> +wget -r -l1 -c -N --no-parent --no-host-directories --cut-dirs=2 -A "index-4211*.fits" -P ~/index_files/ http://broiler.astrometry.net/~dstn/4200/
Missing newline character - you can make atom insert these for you.

2020-10-07 01:49 UTC, danjampro commented on docker/plate_solve_directory.py
> +            pass
Missing newline character - you can make atom insert these for you.

2020-10-07 01:49 UTC, danjampro commented on docker/bash_config.sh
> +export SOLVE_FIELD=$(which solve-field)
Missing newline character - you can make atom insert these for you.

2020-10-07 01:49 UTC, danjampro commented on docker/astrometry_compile.sh
> +# export PKG_CONFIG_PATH=/usr/lib/pkgconfig:/usr/lib64/pkgconfig
If we don't need these env variables, I would remove the comments.

2020-10-07 01:49 UTC, danjampro commented on docker/astrometry_compile.sh
> +# NETPBM_INC ?= -I/usr/include/netpbm
Remove these comments.

2020-10-07 01:49 UTC, danjampro commented on docker/astrometry_compile.sh
> +#! /bin/bash
Why do we need a script? Why not just put all this in the dockerfile?

2020-10-07 01:49 UTC, danjampro commented on docker/astrometry_compile.sh
> +sed -i "s/$ORIGINAL_LINE_START/$REPLACE_WITH/g" makefile.netpbm
Is this really the best way of installing astrometry.net? Seems a bit involved.

2020-10-07 01:49 UTC, danjampro commented on docker/plate_solve_directory.py
> +    logger = logging.getLogger('main-log')
Logging should be handled consistently throughout the project, i.e. via the `HuntsmanBase` class. I'm not sure why you have separated the loggers out into `debug` etc. I think you should be using `logger.debug("message")` instead.

2020-10-07 01:49 UTC, danjampro commented on docker/plate_solve_directory.py
> +        try:
Can you add some comments about what all these `try` `except` statements are trying to achieve?

2020-10-07 01:49 UTC, danjampro commented on docker/plate_solve_directory.py
> +        debug_logger.warning(f"get_solve_field() Timed out on {fpath} with error: \n{e}\n")
Not sure we need to be adding newline characters for logger messages generally.

2020-10-07 01:49 UTC, danjampro commented on docker/plate_solve_directory.py
> +    parser.add_argument('--path', type=str, default="./", help="Directory to search for files for processing.")
These lines look like they are longer than 100 characters.

2020-10-07 01:49 UTC, danjampro commented on docker/plate_solve_directory.py
> +    for dirpath, dirnames, filenames in os.walk(args.path):
Add comments for each of these code blocks

2020-10-07 01:49 UTC, danjampro commented on docker/plate_solve_directory.py
> +#!/usr/bin/python3
I'm not sure what the purpose is of this script - can you add a docstring to the top. Shouldn't it be in the `/scripts` directory?

2020-10-07 01:49 UTC, danjampro commented on docker/plate_solve_directory.py
> +    logger = logging.getLogger('main-log')
See comments above about logging. Maybe we need to include a `get_logger` function to help us load the logger consistently outside of `HuntsmanBase`.

2020-10-07 01:49 UTC, danjampro commented on scripts/download_index_files.sh
> +#! /bin/bash
A lot of commented lines here. I'm not sure we need to keep the tutorial documentation inside our own files, but might be nicer to give a link to the documentation. Can you give a short description of why we need these files somewhere?

2020-10-07 01:49 UTC, danjampro commented on docker/dockerfile
> +
In general we want to avoid using multiple `RUN` commands because they can increase the size of the containers. It would be good to move all `yum` installs to a single line, same goes for pip. I'm also not sure why you need to install cfitsio here, as this should be installed already. Same goes for git, gcc, make , fitsio, astropy.

2020-10-07 01:49 UTC, danjampro commented on docker/dockerfile
> +ADD ./plate_solve_directory.py .
Why not leave this as a script in `/scripts/astrometry`?

2020-10-07 02:40 UTC, fergusL commented on docker/astrometry_compile.sh
> +#! /bin/bash
Just figured it makes the dockerfile a bit easier to follow. Can just pull everything out the script and put it into the docker file

2020-10-07 02:44 UTC, fergusL commented on docker/astrometry_compile.sh
> +sed -i "s/$ORIGINAL_LINE_START/$REPLACE_WITH/g" makefile.netpbm
You can install by apt but I have had issues with that in the past.. not sure how reliable it is now. In any case the LSST docker base image is centOS not ubuntu so can't use apt(?) anyway.

2020-10-07 02:51 UTC, fergusL commented on docker/dockerfile
> +ADD ./plate_solve_directory.py .
you can only specify one docker build context, which atm is `${HUNTSMAN_DRP}/docker`. I think I had it in scripts originally and moved it to be within the build context. If there is no issue with changing the context to just be the entire repo then I can move it back to /scripts/

2020-10-07 03:04 UTC, fergusL commented on docker/plate_solve_directory.py
> +        debug_logger.warning(f"get_solve_field() Timed out on {fpath} with error: \n{e}\n")
The error messages that come out of solve_field errors can be several lines long, I find it hard to read the logs without the spaces

2020-10-07 03:06 UTC, wtgee commented on docker/plate_solve_directory.py
> +        debug_logger.warning(f"get_solve_field() Timed out on {fpath} with error: \n{e}\n")
In general with errors you want to format them `raw`, which should make it more readable:

```suggestion
        debug_logger.warning(f"get_solve_field() Timed out on {fpath} with error: {e!r}")
```

2020-10-13 00:54 UTC, danjampro reviewed
Hi @fergusL, looks good. Just a few minor comments below. Having said that, something in this PR is causing the tests to fail. It looks like something is breaking the `eups` setup of `huntsman-drp` inside the docker container. Once that is fixed I can approve!

2020-10-13 00:54 UTC, danjampro commented on README.md
> +
I've moved most of the readme stuff into the wiki because its easier to edit. There you can find seconds on testing etc, so a lot of this can be removed. Maybe you can move your description to a new wiki page called "astrometry.net"?

2020-10-13 00:54 UTC, danjampro commented on scripts/astrometry/plate_solve_directory.py
> +"""Script to plate solve all fits/fits.fz files in a given directory.
Can you add to this to make it clear that it will modify the FITS headers?

2020-10-15 03:05 UTC, merged