Master calib archiving
AstroHuntsman/huntsman-drp pull request #53
Opened 2020-11-05 22:31 UTC by danjampro

2020-11-06 07:08 UTC, fergusL requested changes
LGTM but needs a mounted volume for archiving the master calibs

2020-11-06 07:08 UTC, fergusL commented on scripts/calibs/make_regular_calibs.py
> +        self.logger = get_logger()
Maybe this class should just inherit from HuntsmanBase?

2020-11-06 07:08 UTC, fergusL commented on src/huntsman/drp/butler.py
> +                metadata["filename"] = archived_filename
So the filename we store in the master calib datatable is going to be based on the directory structure of the docker container? I guess we aren't ever going to be querying the datatable outside of a docker container...

Docker-compose files need to be updated to mount an external volume to `${LSST_HOME}/huntsman-archive/calibs`

2020-11-06 07:08 UTC, fergusL commented on src/huntsman/drp/lsst_tasks.py
> +        nodes (int): The number of processes to use per node.
```suggestion
        procs (int): The number of processes to use per node.
```

2020-11-06 07:08 UTC, fergusL commented on src/huntsman/drp/tests/conftest.py
> +    # Remove the metadata from the DB ready for other tests
Can't you just change the scope of the fixture instead of doing this?

2020-11-09 22:29 UTC, danjampro commented on scripts/calibs/make_regular_calibs.py
> +        self.logger = get_logger()
Good point, I forgot about that.

2020-11-09 22:31 UTC, danjampro commented on src/huntsman/drp/butler.py
> +                metadata["filename"] = archived_filename
hmmm yes, good point about the filenames. Perhaps we should only store relative filenames and join them with the appropriate calib directory somehow...

2020-11-09 22:34 UTC, danjampro commented on src/huntsman/drp/tests/conftest.py
> +    # Remove the metadata from the DB ready for other tests
Unfortunately not, because the `mongodb` instance is not a python entity but a docker service. The only way that I know of clearing the table is either to delete the whole table (I don't want to implement this in case someone accidentally calls it on the actual tables) or to manually remove each entry (which requires a bit more effort).

2020-11-09 22:46 UTC, danjampro commented on src/huntsman/drp/butler.py
> +                metadata["filename"] = archived_filename
@fergusL the alternative is that we mount the host calib archive directory with the same path inside the docker container. So it would look something like `-v ${HUNTSMAN_CALIB_DIR}:${HUNTSMAN_CALIB_DIR}`. Thoughts?

2020-11-10 00:30 UTC, fergusL approved these changes
LGTM

2020-11-10 00:31 UTC, merged